name: Build Module

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Gradle Automation Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Build with Gradle
        run: ./gradlew module:assemble

      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          riruReleaseName=`ls module/build/outputs/magisk/riru/release/*.zip | awk -F '(/|.zip)' '{print $7}'` && echo "riruReleaseName=$riruReleaseName-release" >> $GITHUB_OUTPUT
          riruDebugName=`ls module/build/outputs/magisk/riru/debug/*.zip | awk -F '(/|.zip)' '{print $7}'` && echo "riruDebugName=$riruDebugName-debug" >> $GITHUB_OUTPUT
          zygiskReleaseName=`ls module/build/outputs/magisk/zygisk/release/*.zip | awk -F '(/|.zip)' '{print $7}'` && echo "zygiskReleaseName=$zygiskReleaseName-release" >> $GITHUB_OUTPUT
          zygiskDebugName=`ls module/build/outputs/magisk/zygisk/debug/*.zip | awk -F '(/|.zip)' '{print $7}'` && echo "zygiskDebugName=$zygiskDebugName-debug" >> $GITHUB_OUTPUT
          unzip module/build/outputs/magisk/riru/release/*.zip -d ifw-riru-release
          unzip module/build/outputs/magisk/riru/debug/*.zip -d ifw-riru-debug
          unzip module/build/outputs/magisk/zygisk/release/*.zip -d ifw-zygisk-release
          unzip module/build/outputs/magisk/zygisk/debug/*.zip -d ifw-zygisk-debug

      - name: Upload riru release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.riruReleaseName }}
          path: "./ifw-riru-release/*"

      - name: Upload riru debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.riruDebugName }}
          path: "./ifw-riru-debug/*"

      - name: Upload zygisk release
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskReleaseName }}
          path: "./ifw-zygisk-release/*"

      - name: Upload zygisk debug
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.zygiskDebugName }}
          path: "./ifw-zygisk-debug/*"
